### PR TITLE
Integrate drf-yasg for doc ui and document existing apis

### PR DESCRIPTION
**Pull request by sks444**
This pr integrates with https://github.com/axnsan12/drf-yasg which will provide a nice UI to interact with all the APIs that we have.

Most of the information which one needs to interact with the APIs are automatically generated by `drf-yasg` and additional information can also be added inform of a doc string to the views.

This UI is currently available at `/api/doc/` endpoint.

Screenshot 2020-07-30 at 7 39 29 PM

### CODE REVIEW

**Comment by frjo** [comment]
This looks nice!

**Comment by frjo** [comment]
What happens one day when we have "api/v2"? How will this documentation handle that?

**Comment by sks444** [comment]
@frjo, thanks for noticing that, made the current doc path to `api/v1/doc`. So when we support v2, we would just have to define `api/v2/doc` including v2 url patterns.

**Comment by frjo** [comment]
Merging this in to master, nice work!

**Pull request merged**
