### PR TITLE
React app: Add Reviews

### PR DESCRIPTION
**Pull request by sks444**
Towards https://github.com/OpenTechFund/hypha/issues/2068

### CODE REVIEW

**Comment by sks444** [comment]
https://github.com/OpenTechFund/hypha/issues/2068#issuecomment-679629681

**Review by frjo — CHANGES_REQUESTED** [review]
The docs at /api/v1/doc/ gives a Fetch error with this PR. Can you have look at that please. The nice docs you added makes it a lot easier to test the API.

**Comment by sks444** [comment]
@frjo fixed the doc error.

Actually the review apis that we have in this pr are complex and uses custom dynamic serializers, which the doc is not able to detect while schema generation, so we might not be able to use the doc to test `post` and `put` review apis, others should work fine but the doc doesn't have proper support for the apis with a lot of customizations.

For `post` and `put` on review apis we can use drfs inbuilt ui doc. E.g. by directly going to the url `http://apply.localhost:8000/api/v1/submissions/39/reviews/112/`

Or we are using [postman](https://www.postman.com/) to collaborate internally. [Here is the url](https://www.getpostman.com/collections/178e1fa1125d035e6b00) for postman collection of all the review apis which can be imported for testing purposes.

P.S. I will also write tests for all the apis in a few days, which should make it very easy for review and also help to detect/fix bugs.

**Review by frjo — APPROVED** [review]

**Comment by frjo** [comment]
@sks444 Seems to work and if there are any bugs it does not effect the rest of the site.

Would you like me to merge this in to master or is it better do keep in a separate branch. Will do what you feel is best from your dev perspective.

**Comment by sks444** [comment]
@frjo, I think it would be better to keep it on a separate branch for now. And I will make PRs to this branch for bug fixes or improvements while frontend implementations and testing.

We could also merge this into master but the only reason I don't feel good about merging is that the apis doesn't have tests and while these changes doesn't affect rest of the site, some of the apis might be prone to vulnerabilities. E.g., Exposing data which shouldn't be exposed to a specific user, etc.

**Comment by sks444** [comment]
@frjo, we merged the frontend work here so there is only pr to be taken care of for this feature. This can be deployed to test for testing `Add reviews` in react app.

**Comment by frjo** [comment]
@sks444 Deployed to test now.

**Comment by Parbhat** [comment]
Noticed a few bugs, we are fixing those.

**Comment by sks444** [comment]
@frjo, we have fixed a few bugs on this, can we redeploy.

**Comment by frjo** [comment]
@sks444 Redeploying to test now. 

When possible, it easier to merge when commits are only added and not rewritten to branches that has been merged in to test once.

**Comment by Parbhat** [comment]
@frjo We have fixed all the detected bugs. It can now be redeployed to test for feedback. We may also need a Review detail page in React. Currently, we can add Review, edit and delete. The edit and delete buttons are shown on the review detail page in normal Django views. So, after getting this deployed we can work on review detail feature.

**Comment by frjo** [comment]
@Parbhat Deploying to test now.

**Comment by Parbhat** [comment]
@frjo The add review PR is ready for final review and then can be deployed to production. We have tested it thoroughly.

**Review by frjo — APPROVED** [review]
Nice work!

**Pull request merged**
